SELECT
    *
from
    customer_behav.public.customer 
    
-- Total Revenue generated by customer_segment
SELECT
    customer_segment,
    Sum(sales) AS Revenue
FROM
    customer_behav.public.customer
group by
    customer_segment;

-- top customers
select
    customer_name,
    avg(sales) as Spending
FROM
    customer_behav.public.customer
group by
    customer_name
order by
    avg(sales) desc
limit
    5 
    
-- bottom customers
select
    customer_name,
    avg(sales) as Spending
FROM
    customer_behav.public.customer
group by
    customer_name
order by
    avg(sales) asc
limit
    5 
    
-- Compare average amaount spending on Standard and Express Shipping
select
    ship_mode as Shipping, avg(sales) as Spending
from
    customer_behav.public.customer
group by 
    ship_mode
order by 
    avg(sales) desc 

-- Top 5 products have higher purchase percentage with discount applied?
SELECT
    product_name,
    ROUND(
        100.0 * SUM(CASE WHEN discount > 0 THEN 1 ELSE 0 END) / COUNT(*),
        2
    ) AS discount_purchase_percentage
FROM
    customer_behav.public.customer
GROUP BY
    product_name
ORDER BY
    discount_purchase_percentage DESC
LIMIT 5;

-- Segment customers into New, Normal and Loyal Customers based on thier previous purchases, and show count of each segment
with customer_type as (
SELECT
  customer_id,quantity_ordered_new,
  case
    when quantity_ordered_new =1 then 'New'
    when quantity_ordered_new between 2 and 10 then 'Normal'
    when quantity_ordered_new >10 then 'Loyal'
    -- else 'Loyal'
    end as customer_segment
from 
  customer_behav.public.customer
 )
SELECT
  customer_segment, count(*) as "Numbers of Customer"
from customer_type
group by customer_segment
